#!/usr/bin/env node

const args = process.argv.slice(2);

const semverRegexp =
  /^([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/;

if (args.length != 1) {
  throw new Error("Invalid number of arguments" + args);
}

const tag = args[0];

// Version in format: kafka-v0.0.1

const versionParts = tag.split("@");
if (versionParts.length == 2) {
  const name = versionParts[0];
  const tagVersion = versionParts[1].substring(1);
  const packageVersion =
    require(`../../packages/${name}-sdk/package.json`).version;
  if (packageVersion != tagVersion) {
    throw new Error(
      `Invalid tag. Tag should match package.json version: ${packageVersion} version: ${tagVersion}`
    );
  }
  return console.log("yarn workspace @rhoas/" + name + "-sdk exec npm publish");
}

const fullVersion = tag.substring(1);
if (fullVersion.match(semverRegexp)) {
  // Full release of SDKs
  return console.log(`yarn workspace exec npm publish`);
}

throw new Error("Invalid tag");
