name: Generate API clients
on:
  push:
    branches:
      - main
    paths:
      - ".openapi/**"

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.16
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js  
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
      - name: Generate API clients
        run: yarn generate
      - uses: peter-evans/create-pull-request@v4
        with:
          title: "chore(all): re-generate OpenAPI client(s)"
          token: "${{ secrets.CI_USER_TOKEN }}"
          commit-message: "chore(all): re-generate OpenAPI client(s)"
          author: "app-services-ci <app-services-ci@users.noreply.github.com>"
          branch: chore/generate-api-clients
          branch-suffix: timestamp
          reviewers: '@redhat-developer/app-services-sdk-maintainers'
          delete-branch: suffix
          body: |
            _This pull request was auto-generated_

            This PR adds the latest generated API clients.

            **Actions**:

              1. Review changes and validate against the examples.
              2. Make changes where necessary.
              3. Approve and merge with proper commit message tha represents change
              
              NOTE: After merge separate PR will be created for generation of errors SDK.
