name: Generate Errors SDK
on:
  push:
    branches:
      - main
    paths:
      - "packages/**"

jobs:
  generateErrors:
    env:
      CLIENT_ID: ${{ github.event.client_payload.id }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch Errors JSON files
        run: ./scripts/fetch-errors.sh
      - name: Generate Errors SDK
        run: ./scripts/generate-errors.sh
      - uses: peter-evans/create-pull-request@v3
        with:
          title: "chore(all): re-generate OpenAPI client(s)"
          token: "${{ secrets.CI_USER_TOKEN }}"
          commit-message: "chore(all): re-generate OpenAPI client(s)"
          author: "app-services-ci <app-services-ci@users.noreply.github.com>"
          branch: chore/generate-api-clients
          branch-suffix: timestamp
          reviewers: craicoverflow, wtrocki
          delete-branch: true
          body: |
            _This pull request was auto-generated_

            This PR adds the latest generated ERROR SDKs .

            **Actions**:

              1. Review changes
              2. Approve and merge.
              3. Create a release if needed